export const data = [
    {
      id: "BUD-101",
      description: "Office Rent Payment",
      department: "Administration",
      sponsor: "Corporate Office",
      approved: "100,000,000 VND",
      remaining: "50,000,000 VND",
    },
    {
      id: "BUD-102",
      description: "Annual Team Building",
      department: "Human Resources",
      sponsor: "Employee Welfare Fund",
      approved: "80,000,000 VND",
      remaining: "60,000,000 VND",
    },
    {
      id: "BUD-103",
      description: "Cloud Server Subscription",
      department: "IT",
      sponsor: "Tech Support Fund",
      approved: "120,000,000 VND",
      remaining: "90,000,000 VND",
    },
    {
      id: "BUD-104",
      description: "Marketing Campaign - Spring Sale",
      department: "Marketing",
      sponsor: "Branding Initiative",
      approved: "200,000,000 VND",
      remaining: "150,000,000 VND",
    },
    {
      id: "BUD-105",
      description: "Research and Development Grant",
      department: "R&D",
      sponsor: "Innovation Fund",
      approved: "300,000,000 VND",
      remaining: "280,000,000 VND",
    },
    {
      id: "BUD-106",
      description: "Sales Incentive Program",
      department: "Sales",
      sponsor: "Revenue Growth Fund",
      approved: "50,000,000 VND",
      remaining: "25,000,000 VND",
    },
    {
      id: "BUD-107",
      description: "Employee Training Sessions",
      department: "HR",
      sponsor: "Learning and Development",
      approved: "70,000,000 VND",
      remaining: "40,000,000 VND",
    },
    {
      id: "BUD-108",
      description: "Corporate Social Responsibility Events",
      department: "CSR",
      sponsor: "Charity Funds",
      approved: "150,000,000 VND",
      remaining: "100,000,000 VND",
    },
    {
      id: "BUD-109",
      description: "New Office Furniture",
      department: "Administration",
      sponsor: "Facility Upgrade Budget",
      approved: "60,000,000 VND",
      remaining: "40,000,000 VND",
    },
    {
      id: "BUD-110",
      description: "Cybersecurity Tools Update",
      department: "IT",
      sponsor: "Risk Management",
      approved: "90,000,000 VND",
      remaining: "70,000,000 VND",
    },
  ];
  