import Layout from "../../../components/Layout"
import Head from "next/head";
import { data } from "./data_demo";
import { useRouter } from 'next/router';
import { House , Search, X} from 'lucide-react';

export default function Budget() {
  const router = useRouter();
  const backToHome = ()=>{
    router.push(`/`)
  }
  return (
    <div className="">
      <Head>
        <title>CSBU management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Layout>
        <div className="p-6 w-full bg-white shadow-md rounded-md">
          <div className="flex items-center text-gray-600 space-x-2 mb-4">
            <span className="text-gray-500 group" onClick={()=> backToHome()}>
              <House className="text-gray-500 group-hover:text-black transition-colors duration-300" size={20}/>
            </span>
            <span className="text-gray-400">/</span>
            <span className="text-l font-semibold">Budget</span>
          </div>
          <hr></hr>
          <h1 className="text-2xl font-semibold mb-4 mt-4">Budget Management</h1>
          <SearchBar />
          <Table />
        </div>
      </Layout>

    </div>
  );
}
const SearchBar = () => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
      <input
        type="text"
        placeholder="Search by Budget Code/Description"
        className="border rounded-md p-2 focus:outline-none focus:ring-1 focus:ring-green-500"
      />
      <select className="border rounded-md p-2 focus:outline-none focus:ring-1 focus:ring-green-500">
        <option>Select year</option>
        <option>2024</option>
        <option>2023</option>
      </select>
      <div className="flex flex-col md:flex-row space-x-0 md:space-x-2">
        <button className="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 transition flex items-center space-x-2 mb-2 md:mb-0">
          <Search size={15} />
          <span className="ml-2">Search</span>
        </button>
        <button className="bg-gray-400 text-white px-4 py-2 rounded-md hover:bg-gray-500 transition flex items-center space-x-2">
          <X size={15} />
          <span className="ml-2">Reset</span>
        </button>
      </div>
    </div>
  );
}

const Table = ()=> {
  

  return (
    <div className="overflow-x-auto">
      <table className="table-auto w-full text-sm text-left border-collapse border border-gray-300">
        <thead className="bg-gray-100">
          <tr>
            <th className="border px-4 py-2">Budget Code</th>
            <th className="border px-4 py-2">Description</th>
            <th className="border px-4 py-2">Control Department</th>
            <th className="border px-4 py-2">Funding Department</th>
            <th className="border px-4 py-2">Approved Amount</th>
            <th className="border px-4 py-2">Remaining Amount</th>

          </tr>
        </thead>
        <tbody>
          {data.map((row, index) => (
            <tr key={index} className="hover:bg-gray-100">
              <td className="border px-4 py-2">{row.id}</td>
              <td className="border px-4 py-2">{row.description}</td>
              <td className="border px-4 py-2">{row.department}</td>
              <td className="border px-4 py-2">{row.sponsor}</td>
              <td className="border px-4 py-2">{row.approved}</td>
              <td className="border px-4 py-2">{row.remaining}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="flex justify-between items-center mt-4">
        <span className="text-sm text-gray-600">1-10 của 76 Mục</span>
        <div className="flex space-x-1">
          <button className="px-2 py-1 bg-gray-200 rounded hover:bg-gray-300">1</button>
          <button className="px-2 py-1 bg-gray-100 rounded hover:bg-gray-300">2</button>
          <button className="px-2 py-1 bg-gray-100 rounded hover:bg-gray-300">3</button>
          <span>...</span>
          <button className="px-2 py-1 bg-gray-100 rounded hover:bg-gray-300">10</button>
        </div>
      </div>
    </div>
  );
}
