import Head from "next/head";
import Layout from "../components/Layout";
import { FinanceManagement } from "../data/NavBarData";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>CSBU management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Layout>
        Home
      </Layout>
    </div>
  );
}
